// Generated by gencpp from file learn_service/IntPlusResponse.msg
// DO NOT EDIT!


#ifndef LEARN_SERVICE_MESSAGE_INTPLUSRESPONSE_H
#define LEARN_SERVICE_MESSAGE_INTPLUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learn_service
{
template <class ContainerAllocator>
struct IntPlusResponse_
{
  typedef IntPlusResponse_<ContainerAllocator> Type;

  IntPlusResponse_()
    : result(0)  {
    }
  IntPlusResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::learn_service::IntPlusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learn_service::IntPlusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IntPlusResponse_

typedef ::learn_service::IntPlusResponse_<std::allocator<void> > IntPlusResponse;

typedef boost::shared_ptr< ::learn_service::IntPlusResponse > IntPlusResponsePtr;
typedef boost::shared_ptr< ::learn_service::IntPlusResponse const> IntPlusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learn_service::IntPlusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learn_service::IntPlusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learn_service::IntPlusResponse_<ContainerAllocator1> & lhs, const ::learn_service::IntPlusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learn_service::IntPlusResponse_<ContainerAllocator1> & lhs, const ::learn_service::IntPlusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learn_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learn_service::IntPlusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_service::IntPlusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_service::IntPlusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_service::IntPlusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_service::IntPlusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_service::IntPlusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learn_service::IntPlusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::learn_service::IntPlusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::learn_service::IntPlusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learn_service/IntPlusResponse";
  }

  static const char* value(const ::learn_service::IntPlusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learn_service::IntPlusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 result\n"
;
  }

  static const char* value(const ::learn_service::IntPlusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learn_service::IntPlusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntPlusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learn_service::IntPlusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learn_service::IntPlusResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARN_SERVICE_MESSAGE_INTPLUSRESPONSE_H
