// Generated by gencpp from file learn_service/IntPlus.msg
// DO NOT EDIT!


#ifndef LEARN_SERVICE_MESSAGE_INTPLUS_H
#define LEARN_SERVICE_MESSAGE_INTPLUS_H

#include <ros/service_traits.h>


#include <learn_service/IntPlusRequest.h>
#include <learn_service/IntPlusResponse.h>


namespace learn_service
{

struct IntPlus
{

typedef IntPlusRequest Request;
typedef IntPlusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IntPlus
} // namespace learn_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learn_service::IntPlus > {
  static const char* value()
  {
    return "32f3e69fccd784eebfbfc5b37be0e2f0";
  }

  static const char* value(const ::learn_service::IntPlus&) { return value(); }
};

template<>
struct DataType< ::learn_service::IntPlus > {
  static const char* value()
  {
    return "learn_service/IntPlus";
  }

  static const char* value(const ::learn_service::IntPlus&) { return value(); }
};


// service_traits::MD5Sum< ::learn_service::IntPlusRequest> should match
// service_traits::MD5Sum< ::learn_service::IntPlus >
template<>
struct MD5Sum< ::learn_service::IntPlusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learn_service::IntPlus >::value();
  }
  static const char* value(const ::learn_service::IntPlusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_service::IntPlusRequest> should match
// service_traits::DataType< ::learn_service::IntPlus >
template<>
struct DataType< ::learn_service::IntPlusRequest>
{
  static const char* value()
  {
    return DataType< ::learn_service::IntPlus >::value();
  }
  static const char* value(const ::learn_service::IntPlusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learn_service::IntPlusResponse> should match
// service_traits::MD5Sum< ::learn_service::IntPlus >
template<>
struct MD5Sum< ::learn_service::IntPlusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learn_service::IntPlus >::value();
  }
  static const char* value(const ::learn_service::IntPlusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_service::IntPlusResponse> should match
// service_traits::DataType< ::learn_service::IntPlus >
template<>
struct DataType< ::learn_service::IntPlusResponse>
{
  static const char* value()
  {
    return DataType< ::learn_service::IntPlus >::value();
  }
  static const char* value(const ::learn_service::IntPlusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARN_SERVICE_MESSAGE_INTPLUS_H
