// Generated by gencpp from file learn_topic/Information.msg
// DO NOT EDIT!


#ifndef LEARN_TOPIC_MESSAGE_INFORMATION_H
#define LEARN_TOPIC_MESSAGE_INFORMATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learn_topic
{
template <class ContainerAllocator>
struct Information_
{
  typedef Information_<ContainerAllocator> Type;

  Information_()
    : company()
    , year()  {
    }
  Information_(const ContainerAllocator& _alloc)
    : company(_alloc)
    , year(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _company_type;
  _company_type company;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _year_type;
  _year_type year;





  typedef boost::shared_ptr< ::learn_topic::Information_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learn_topic::Information_<ContainerAllocator> const> ConstPtr;

}; // struct Information_

typedef ::learn_topic::Information_<std::allocator<void> > Information;

typedef boost::shared_ptr< ::learn_topic::Information > InformationPtr;
typedef boost::shared_ptr< ::learn_topic::Information const> InformationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learn_topic::Information_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learn_topic::Information_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learn_topic::Information_<ContainerAllocator1> & lhs, const ::learn_topic::Information_<ContainerAllocator2> & rhs)
{
  return lhs.company == rhs.company &&
    lhs.year == rhs.year;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learn_topic::Information_<ContainerAllocator1> & lhs, const ::learn_topic::Information_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learn_topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learn_topic::Information_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_topic::Information_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_topic::Information_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_topic::Information_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_topic::Information_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_topic::Information_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learn_topic::Information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4092f70730c2545e71ae30dda7615194";
  }

  static const char* value(const ::learn_topic::Information_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4092f70730c2545eULL;
  static const uint64_t static_value2 = 0x71ae30dda7615194ULL;
};

template<class ContainerAllocator>
struct DataType< ::learn_topic::Information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learn_topic/Information";
  }

  static const char* value(const ::learn_topic::Information_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learn_topic::Information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string company\n"
"string year\n"
;
  }

  static const char* value(const ::learn_topic::Information_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learn_topic::Information_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.company);
      stream.next(m.year);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Information_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learn_topic::Information_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learn_topic::Information_<ContainerAllocator>& v)
  {
    s << indent << "company: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.company);
    s << indent << "year: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.year);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARN_TOPIC_MESSAGE_INFORMATION_H
